name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - {{ cookiecutter.main_branch }}
  pull_request:
    branches:
      - {{ cookiecutter.main_branch }}
{% raw %}
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
{%- endraw %}
          python-version: "{{ cookiecutter.python_version }}"
{%- raw %}
          cache: "pipenv"
      - name: Install pipenv
        run: pip install pipenv
      - name: Sync
        run: pipenv sync --dev
      - name: Test
        run: make ci
{%- endraw %}
