version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.7
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          command: pipenv install --dev
      - run:
          command: pipenv run test

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test
